### ISSUE TITLE
根据论文写配置

### ISSUE THREAD

**Issue by 2805651606** [verlab/accelerated_features#76]
0%|                                                                                                                                                                                            | 0/160000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/xfeat/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/miniconda3/envs/xfeat/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data3/WSX/accelerated_features/modules/training/train_28.py", line 371, in <module>
    trainer.train()
  File "/data3/WSX/accelerated_features/modules/training/train_28.py", line 239, in train
    p1 = torch.cat([p1s, p1], dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 600 but got size 608 for tensor number 1 in the list.
我看论文里面图片格式是800，600.我改成之后，运行不了。

**Comment by Xiaole-An** [comment]
HI @2805651606 除了在train里面改动尺寸外，MegaDepthDataset类里也需要改动，你看一下是不是忘记改了。要保证megadepth和warpedCOCO尺寸一样的

**Comment by 2805651606** [comment]
好的谢谢。解决了。
我用你最新发布的评估代码，然后
R_err: 0.07105973478560063, t_err: 0.3281071596782389, Inliers: 0
R_err: 0.13242374205641105, t_err: 0.5692219281803291, Inliers: 0
R_err: 2.0303554516149402, t_err: 9.69551256971788, Inliers: 0
R_err: 1.112681358295564, t_err: 6.819630126296131, Inliers: 0
R_err: 17.15245130998925, t_err: 49.769504454113004, Inliers: 0
R_err: 0.06970964298552414, t_err: 0.2497385048637756, Inliers: 0
R_err: 0.37633511515468315, t_err: 0.4877891889008318, Inliers: 0
R_err: 0.05859537991632689, t_err: 0.28733090161078995, Inliers: 0
R_err: 1.3132266746441483, t_err: 4.702368153727258, Inliers: 0
R_err: 0.0821689290087214, t_err: 0.2963301226338091, Inliers: 0
R_err: 0.11980112699062619, t_err: 0.7924706402811298, Inliers: 0
R_err: 0.3103344789991813, t_err: 1.9342218570046488, Inliers: 0
一个匹配点也找不到，这是因为我之前训练用的图片分辨率用的800*608的缘故？

**Comment by 2805651606** [comment]
你好，论文中关于HPatches数据集评估和Aachen day-night评估的代码有？
@Xiaole-An

**Comment by Xiaole-An** [comment]
> 你好，论文中关于HPatches数据集评估和Aachen day-night评估的代码有？ [@Xiaole-An](https://github.com/Xiaole-An)

我也不是作者哈~
当时我用的内点率大致看了一下，评估的话你可以参考一下 #32 不知道是否对你有用

**Comment by 2805651606** [comment]
好的，谢谢

**Comment by OUCmeenoi** [comment]
> 好的，谢谢

请问你现在找到了hpatched和aachen的评估代码了吗
