### ISSUE TITLE
xfeat.pt替换xfeat-lighterglue.pt为什么是这样呀

### ISSUE THREAD

**Issue by MingYangGeng** [verlab/accelerated_features#82]
Traceback (most recent call last):
  File "C:\Users\GMY\Desktop\test\pipei\1\accelerated_features-main\xfeat_torch_hub_example-lg.py", line 119, in <module>
    canvas = warp_corners_and_draw_matches(mkpts_0, mkpts_1, im1, im2)
  File "C:\Users\GMY\Desktop\test\pipei\1\accelerated_features-main\xfeat_torch_hub_example-lg.py", line 49, in warp_corners_and_draw_matches
    H, mask = cv2.findHomography(ref_points, dst_points, cv2.USAC_MAGSAC, 3.5, maxIters=1_000, confidence=0.999)
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\usac\ransac_solvers.cpp:1047: error: (-2:Unspecified error) in function 'auto __cdecl cv::usac::mergePoints::<lambda_75a5199e177ff79adf36a186386ef799>::operator ()(class cv::Mat &,int) const'
> Invalid dimension of point (expected: 'points.cols >= pt_dim'), where
>     'points.cols' is 0
> must be greater than or equal to
>     'pt_dim' is 2

进程已结束，退出代码为 1

**Comment by schwert26** [comment]
xfeat.pt只有xfeat模型的权重，应该将lightglue模型再你自己的数据集下训练导出pt文件
